### ISSUE TITLE
Software support unavailable for Linux users

### ISSUE THREAD

**Issue by samiurprapon** [aaneloy/CSE331L-Section-10-Fall20-NSU#1]
**1. EMU8086 
2. Proteus, MikroC, PicKit3**

Please add alternatives along with those softwares.

**Comment by aaneloy** [comment]
There is no alternative to EMU8086 and other software. What you can do, create a Virtual machine inside the ubuntu distributor and run Windows 10 there. Alternatively, Wine is a good option too, but Proteus will not run there. So the best shot will be to use Windows 10 inside a Virtual Machine.

Some useful links are attached.

1. Virtual Machine Setup - https://itsfoss.com/install-windows-10-virtualbox-linux/
2. Wine setup - https://www.linux.com/training-tutorials/how-install-and-use-wine-run-windows-applications-linux/
