### ISSUE TITLE
GitHub fetch speed extremely low 

### ISSUE THREAD

**Issue by kayesIbnaQayumNSU** [aaneloy/CSE331L-Section-10-Fall20-NSU#3]
Dear bhaiya,

For some reasons, when I want to fetch, sometimes download speed drops to extremely low speed, Maximum 5 KB. also tried with mobile data but could not fix this issue.

Sincerely
kayes ibna qayum

**Comment by aaneloy** [comment]
Please try closing other browsing or downloading windows.
